[package]
name = "presencejj"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unused_variables = "allow"
unused_assignments = "allow"

[dependencies]
rfd = "0.17.2"
office = "0.8"
lazy_static = "1.5"
regex = "1.12"
chrono = { version = "0.4.44", features = ["serde"] }
rand = "0.10.1"
console = "0.16.3"
dialoguer = "0.12.0"
tempfile = "3.27"
strum = "0.28"
strum_macros = "0.28"
rust_xlsxwriter = "0.94.1"
ratatui = {version="0.30.*", features=["unstable-widget-ref", "unstable-rendered-line-info"]} # 0.30.0
crossterm = "0.29"
color-eyre = "0.6"
# textwrap = "0.16"
unicode-segmentation = "1.13"
# unicode-width = "0.2.*"
# ratatui_input = "0.1"
ratatui-textarea = "*"
# typst-bake = "0.1.9"
typst-as-lib = "0.15.4"
typst = "0.14.2"
typst-pdf = "0.14.2"
serde = { version = "1", features = ["derive", "rc"] }

# [package.metadata.typst-bake]
# template-dir = "./templates"
# fonts-dir = "./fonts"