#import "template.typ": *
#let site = [Joseph de Sérigny]
#let saison = [Camp de jour été 2025]
#let semaine = [1]
#let groupes = (
"M7e509e04": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"M6570b232": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"M9e932280": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"Me415efde": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"M43ebd260": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"M309721e3": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"M96db7aa9": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"M5e03bdc0": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"Mb9b50c65": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"Mc0f58d2d": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"M8d013bce": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"M2eb278ff": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"Mf233f33f": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"M672e5f3d": new_groupe(categorie: [Basaltes], discriminant: none, animateur: none, profil: none),
"M74131a50": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: [Sport]),
"M60d21ee9": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: none),
"M0af43e88": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: [Sport]),
"M87e52e04": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: [Sport]),
"M2d764999": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: none),
"M99799ad2": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: none),
"M408b4770": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: none),
"M6e016097": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: [Sport]),
"M9be9bcd9": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: none),
"Md49e501f": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: none),
"M829ce0ad": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: none),
"M72d16283": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: [Sport]),
"M4fc690e4": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: none),
"Mc94f7715": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: [Sport]),
"M0e57976b": new_groupe(categorie: [Crocus], discriminant: none, animateur: none, profil: [Sport]),
"M3cc5ff13": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"Md8c18ed5": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"Me0f09851": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"M0e7ff3e8": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"Mc7dddbbc": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"M7f151601": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"M979748a1": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"M2b31f44c": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"M20b981a4": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"Md43b3e12": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"Mbbb5505e": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"M17f5242a": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"M1fdbc148": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
"M65cc6f7c": new_groupe(categorie: [Balaous], discriminant: none, animateur: none, profil: none),
)
#let participants = (
new_enfant(
		id: "M3cc5ff13",
		nom: [Bernard],
		prenom: [Charles-Antoine],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Mélissa Bernard], tel: none, adresse: none, email: "melber30\@hotmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2018/07/19],
		age: [6],
	),
new_enfant(
		id: "M43ebd260",
		nom: [Boulanger],
		prenom: [Daphnée],
		cam: new_cam(nam: [BOUD16542119], exp_mois: [04], exp_year: [2024]),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Amélie Lepage], tel: none, adresse: none, email: "amelie.lepage\@hotmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: true, ibuprofene: none, antiemetique: true, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Amélie  Lepage], tel: [+1 (514) 831-4788], lien: [Mere]),
		contact_2: new_contact(nom: [Patrice  Boulanger], tel: [+1 (438) 497-4788], lien: [Pere]),
		quitte: ([Parent],),
		mdp: [Jackson],
		piscine: new_piscine(auth_partage: true, vfi: false, tete_sous_eau: true),
		auth_photo: true,
		commentaire: none,
		naissance: [2016/04/21],
		age: [9],
	),
new_enfant(
		id: "M99799ad2",
		nom: [Boulanger],
		prenom: [Elliot],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Amélie Lepage], tel: none, adresse: none, email: "amelie.lepage\@hotmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2018/10/15],
		age: [6],
	),
new_enfant(
		id: "M20b981a4",
		nom: [Bérard],
		prenom: [Noémie],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Mélissa Bérard], tel: none, adresse: none, email: "melisoleil\@hotmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2017/11/01],
		age: [7],
	),
new_enfant(
		id: "Md43b3e12",
		nom: [Cerqueira Silveira],
		prenom: [Valentina],
		cam: new_cam(nam: [CERV18520416], exp_mois: [02], exp_year: [2026]),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Leandro Silveira], tel: none, adresse: none, email: "ldejsilveira\@gmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: false, ibuprofene: none, antiemetique: false, antibiotique: false, acetaminophene: false,),
		contact_1: new_contact(nom: [Leandro De Jesus], tel: [+1 (438) 495-4486], lien: [Père]),
		contact_2: new_contact(nom: [Aline Conceiçao  Cerqueira Silveira], tel: [+1 (514) 501-4386], lien: [Mère]),
		quitte: ([Parent],),
		mdp: [Cerqueira],
		piscine: new_piscine(auth_partage: true, vfi: false, tete_sous_eau: true),
		auth_photo: true,
		commentaire: none,
		naissance: [2018/02/04],
		age: [7],
	),
new_enfant(
		id: "M5e03bdc0",
		nom: [Chassé],
		prenom: [Léo],
		cam: new_cam(nam: [CHAL15033110], exp_mois: [03], exp_year: [2023]),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Maxime Chassé], tel: none, adresse: none, email: "maxcha\@hotmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: true, ibuprofene: none, antiemetique: true, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Maxime Chassé], tel: [+1 (514) 473-3341], lien: [Père]),
		contact_2: new_contact(nom: [Jaelle Champagne], tel: [+1 (514) 518-5778], lien: [Mère]),
		quitte: ([Parent], [Autre: Andrée-Anne Lemieux,
Marc-André Bouchard]),
		mdp: [Pikachu],
		piscine: new_piscine(auth_partage: true, vfi: false, tete_sous_eau: true),
		auth_photo: true,
		commentaire: none,
		naissance: [2015/03/31],
		age: [10],
	),
new_enfant(
		id: "M4fc690e4",
		nom: [Chrétien],
		prenom: [Hayden],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [David Chrétien], tel: none, adresse: none, email: "chretien_david26\@hotmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2019/01/14],
		age: [6],
	),
new_enfant(
		id: "M7e509e04",
		nom: [Chrétien],
		prenom: [Maylie],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [David Chrétien], tel: none, adresse: none, email: "chretien_david26\@hotmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2015/11/30],
		age: [9],
	),
new_enfant(
		id: "M74131a50",
		nom: [Contant],
		prenom: [Mia],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Melissa Contant], tel: none, adresse: none, email: "melissacontant\@me.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2019/09/22],
		age: [5],
	),
new_enfant(
		id: "M1fdbc148",
		nom: [Couillard-Chainé],
		prenom: [Mathilde],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Myriam Couillard-Castonguay], tel: none, adresse: none, email: "myriamcouillard\@gmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2018/04/03],
		age: [7],
	),
new_enfant(
		id: "M6570b232",
		nom: [Couillard-Chainé],
		prenom: [Raphaëlle],
		cam: new_cam(nam: [COUR15602915], exp_mois: [10], exp_year: [2023]),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Myriam Couillard-Castonguay], tel: none, adresse: none, email: "myriamcouillard\@gmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: false, ibuprofene: none, antiemetique: false, antibiotique: false, acetaminophene: false,),
		contact_1: new_contact(nom: [Myraim Couillard-Castonguay], tel: [+1 (514) 632-3474], lien: [Mère]),
		contact_2: new_contact(nom: [Non répondu], tel: none, lien: [Non répondu]),
		quitte: ([Parent], [Autre: Grand-mère Susan Thibodeau ou
Diane Castonguay]),
		mdp: [Mathilde],
		piscine: new_piscine(auth_partage: true, vfi: false, tete_sous_eau: true),
		auth_photo: true,
		commentaire: none,
		naissance: [2015/10/29],
		age: [9],
	),
new_enfant(
		id: "M9e932280",
		nom: [Crépeau],
		prenom: [Noémie],
		cam: new_cam(nam: [CREN15552218], exp_mois: [05], exp_year: [2031]),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Vicky Mégré], tel: none, adresse: none, email: "vmegre\@hotmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: true, ibuprofene: none, antiemetique: false, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Vicky Mégré], tel: [+1 (514) 618-3959], lien: [Mere]),
		contact_2: new_contact(nom: [Olivier Crépeau], tel: [+1 (514) 378-5153], lien: [Pere]),
		quitte: ([Parent],),
		mdp: [2565],
		piscine: new_piscine(auth_partage: true, vfi: false, tete_sous_eau: true),
		auth_photo: true,
		commentaire: none,
		naissance: [2015/05/22],
		age: [10],
	),
new_enfant(
		id: "M2d764999",
		nom: [Crépeau],
		prenom: [Simon],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Vicky Mégré], tel: none, adresse: none, email: "vmegre\@hotmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2019/03/27],
		age: [6],
	),
new_enfant(
		id: "M7f151601",
		nom: [DEKE],
		prenom: [Stessie],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [levy deke], tel: none, adresse: none, email: "levydeke27\@gmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2017/06/02],
		age: [8],
	),
new_enfant(
		id: "M979748a1",
		nom: [Décarie],
		prenom: [Anne],
		cam: new_cam(nam: [DECA17511514], exp_mois: [01], exp_year: [2025]),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Sylvianne Tardif], tel: none, adresse: none, email: "sytar16\@hotmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: true, ibuprofene: none, antiemetique: true, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Sylvianne  Tardif], tel: [+1 (438) 931-2482], lien: [Mere]),
		contact_2: new_contact(nom: [Joseph Décarie], tel: [+1 (514) 209-4473], lien: [Pere]),
		quitte: ([Parent],),
		mdp: [Kikine],
		piscine: new_piscine(auth_partage: true, vfi: true, tete_sous_eau: true),
		auth_photo: true,
		commentaire: none,
		naissance: [2017/01/15],
		age: [8],
	),
new_enfant(
		id: "M65cc6f7c",
		nom: [Farhat],
		prenom: [Zack],
		cam: new_cam(nam: [FARZ18051713], exp_mois: [05], exp_year: [2026]),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: true, just: [Autisme leger]),
		compte: new_compte(mandataire: [Mélanie Wilmotte], tel: none, adresse: none, email: "melanie.wilmotte86\@gmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: false, ibuprofene: none, antiemetique: false, antibiotique: false, acetaminophene: false,),
		contact_1: new_contact(nom: [Melanie Wilmotte], tel: [+1 (514) 568-5636], lien: [Mere]),
		contact_2: new_contact(nom: [Mohamad Farhat], tel: [+1 (514) 815-0254], lien: [Pere]),
		quitte: ([Parent],),
		mdp: [2231],
		piscine: new_piscine(auth_partage: true, vfi: true, tete_sous_eau: false),
		auth_photo: true,
		commentaire: none,
		naissance: [2018/05/17],
		age: [7],
	),
new_enfant(
		id: "M60d21ee9",
		nom: [Grégoire],
		prenom: [Louis],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Martine Desjardins], tel: none, adresse: none, email: "martine.desjardins05\@gmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2018/11/03],
		age: [6],
	),
new_enfant(
		id: "M2eb278ff",
		nom: [Hamelin],
		prenom: [Mathis],
		cam: new_cam(nam: [HAMM15021919], exp_mois: [02], exp_year: [2025]),
		genre: [Homme],
		allergies: ([réagit beaucoup à la piqûre d'insecte (bosse rouge) mais pas allergique],),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [alix handfield], tel: none, adresse: none, email: "alixhand\@gmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: true, ibuprofene: none, antiemetique: true, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Simon Hamelin], tel: [+1 (514) 226-2958], lien: [père]),
		contact_2: new_contact(nom: [Alix Handfield], tel: [+1 (514) 772-8925], lien: [mère]),
		quitte: ([Parent], [Autre: Suzanne Fauteux, grand-mère]),
		mdp: [Coco],
		piscine: new_piscine(auth_partage: true, vfi: true, tete_sous_eau: true),
		auth_photo: true,
		commentaire: none,
		naissance: [2015/02/18],
		age: [10],
	),
new_enfant(
		id: "Mc0f58d2d",
		nom: [Jean],
		prenom: [Landon],
		cam: new_cam(nam: [JEAL14122718], exp_mois: [12], exp_year: [2030]),
		genre: [Homme],
		allergies: ([Pollen], [graminées], [herbes à poux]),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Kim Lafleur], tel: none, adresse: none, email: "kimycruze\@hotmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: true, ibuprofene: none, antiemetique: true, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Kim Lafleur], tel: [+1 (514) 966-5430], lien: [Mère]),
		contact_2: new_contact(nom: [Roosevens Jean], tel: [+1 (514) 583-1645], lien: [Père]),
		quitte: ([Parent], [Autre: Grand mère Chantale Grondin]),
		mdp: [Poussin],
		piscine: new_piscine(auth_partage: true, vfi: false, tete_sous_eau: true),
		auth_photo: true,
		commentaire: none,
		naissance: [2014/12/27],
		age: [10],
	),
new_enfant(
		id: "M72d16283",
		nom: [Landry],
		prenom: [Axelle],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Aude Beaugrand], tel: none, adresse: none, email: "aude-emilie.beaugrand\@hotmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2019/08/27],
		age: [5],
	),
new_enfant(
		id: "Md8c18ed5",
		nom: [Landry],
		prenom: [Malik],
		cam: new_cam(nam: [LANM17020214], exp_mois: [02], exp_year: [2025]),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Aude Beaugrand], tel: none, adresse: none, email: "aude-emilie.beaugrand\@hotmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: true, ibuprofene: none, antiemetique: false, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Aude-Émilie  Beaugrand], tel: [+1 (514) 961-4133], lien: [Mere]),
		contact_2: new_contact(nom: [Pierre-luc  Landry], tel: [+1 (514) 831-1998], lien: [Père]),
		quitte: ([Parent],),
		mdp: [Poulette],
		piscine: new_piscine(auth_partage: true, vfi: true, tete_sous_eau: true),
		auth_photo: true,
		commentaire: none,
		naissance: [2017/02/02],
		age: [8],
	),
new_enfant(
		id: "M87e52e04",
		nom: [Levesque],
		prenom: [Felix],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Michael Levesque], tel: none, adresse: none, email: "michael-l\@hotmail.fr"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2019/09/20],
		age: [5],
	),
new_enfant(
		id: "M2b31f44c",
		nom: [MPENGUEM NGOUPEYOU],
		prenom: [Elvira],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Serge MPENGUEM NGOUPEYOU], tel: none, adresse: none, email: "devinengroupeyou3\@gmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2017/11/30],
		age: [7],
	),
new_enfant(
		id: "M408b4770",
		nom: [MPENGUEM NGOUPEYOU],
		prenom: [Leana],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Serge MPENGUEM NGOUPEYOU], tel: none, adresse: none, email: "devinengroupeyou3\@gmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2019/03/14],
		age: [6],
	),
new_enfant(
		id: "M0af43e88",
		nom: [Manfoumbi],
		prenom: [Gabriel],
		cam: new_cam(nam: [MANG19031910], exp_mois: [03], exp_year: [2027]),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Veronique Manfoumbi], tel: none, adresse: none, email: "m_veronique\@outlook.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: false, ibuprofene: none, antiemetique: false, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Nathalie Manfoumbi], tel: [+1 (438) 886-6284], lien: [Tante]),
		contact_2: new_contact(nom: [Eric Manfoumbi], tel: [+1 (514) 297-2888], lien: [Oncle]),
		quitte: ([Parent], [Autre: Nathalie Manfoumbi (tante]),
		mdp: [Pepto2020],
		piscine: new_piscine(auth_partage: true, vfi: true, tete_sous_eau: false),
		auth_photo: true,
		commentaire: none,
		naissance: [2019/03/19],
		age: [6],
	),
new_enfant(
		id: "M6e016097",
		nom: [Mukandila-Walters],
		prenom: [James],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [bilonda mukandila], tel: none, adresse: none, email: "bmukandila\@hotmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2020/05/30],
		age: [5],
	),
new_enfant(
		id: "Mb9b50c65",
		nom: [N'KOUE],
		prenom: [Lawson Edourado],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Autre],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Leonelle N'KOUE], tel: none, adresse: none, email: "leonellekoue28\@gmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2014/08/30],
		age: [10],
	),
new_enfant(
		id: "M8d013bce",
		nom: [N'KOUE],
		prenom: [Lawson Jordy],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Leonelle N'KOUE], tel: none, adresse: none, email: "leonellekoue28\@gmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2012/10/27],
		age: [12],
	),
new_enfant(
		id: "Mf233f33f",
		nom: [NASRI],
		prenom: [Zayd],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Autre],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Aida NASRI], tel: none, adresse: none, email: "k.nasri.ayda\@gmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2016/01/01],
		age: [9],
	),
new_enfant(
		id: "M0e7ff3e8",
		nom: [Parent],
		prenom: [Raphaël],
		cam: new_cam(nam: [PARR17062112], exp_mois: [06], exp_year: [2025]),
		genre: [Homme],
		allergies: (),
		maladies: ([Asthme],),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Carl Parent], tel: none, adresse: none, email: "accord-77\@hotmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: true, ibuprofene: none, antiemetique: true, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Serge Parent], tel: [+1 (514) 619-3480], lien: [Grand pere]),
		contact_2: new_contact(nom: [Jessika Servant], tel: [+1 (514) 975-8798], lien: [Mere]),
		quitte: ([Parent], [Autre: Grand papa et maman]),
		mdp: [Hockey],
		piscine: new_piscine(auth_partage: true, vfi: true, tete_sous_eau: true),
		auth_photo: true,
		commentaire: none,
		naissance: [2017/06/21],
		age: [7],
	),
new_enfant(
		id: "Mc7dddbbc",
		nom: [RAMALANJAONA],
		prenom: [Kanto],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Autre],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Jaonah Tolotra RAMALANJAONA], tel: none, adresse: none, email: "jaonahtolotra\@gmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2017/08/25],
		age: [7],
	),
new_enfant(
		id: "M0e57976b",
		nom: [RAMALANJAONA],
		prenom: [Manoe],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Autre],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Jaonah Tolotra RAMALANJAONA], tel: none, adresse: none, email: "jaonahtolotra\@gmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2019/12/19],
		age: [5],
	),
new_enfant(
		id: "M309721e3",
		nom: [Rancourt],
		prenom: [Eliott],
		cam: new_cam(nam: [RANE13120614], exp_mois: [12], exp_year: [2029]),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Alexandra Ducharme lapointe], tel: none, adresse: none, email: "aducharmelapointe\@gmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: false,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: false, ibuprofene: none, antiemetique: false, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Alexandra Ducharme lapointe], tel: [+1 (438) 396-6869], lien: [Mere]),
		contact_2: new_contact(nom: [Joel  Rancourt], tel: [+1 (514) 949-9749], lien: [Pere]),
		quitte: ([Parent],),
		mdp: [Teen titan],
		piscine: new_piscine(auth_partage: true, vfi: false, tete_sous_eau: true),
		auth_photo: false,
		commentaire: none,
		naissance: [2013/12/06],
		age: [11],
	),
new_enfant(
		id: "Mbbb5505e",
		nom: [Rivadeneira],
		prenom: [Lucas],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Maude Ménard St-Germain], tel: none, adresse: none, email: "maudemstg31\@gmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2017/11/09],
		age: [7],
	),
new_enfant(
		id: "M829ce0ad",
		nom: [Salamanca],
		prenom: [Antonella],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Cesar Salamanca], tel: none, adresse: none, email: "csalamancaleon\@gmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2019/01/01],
		age: [6],
	),
new_enfant(
		id: "Me415efde",
		nom: [Scott],
		prenom: [Viviane],
		cam: new_cam(nam: [SCOV15580314], exp_mois: [08], exp_year: [2031]),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Véronique Scott], tel: none, adresse: none, email: "scott.veronique\@gmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: false, ibuprofene: none, antiemetique: false, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Véronique Scott], tel: [+1 (514) 808-0797], lien: [mère]),
		contact_2: new_contact(nom: [Pascal Dupont Dorais], tel: [+1 (438) 397-2028], lien: [père]),
		quitte: ([Parent], [Autre: Isabelle Paquin, Sophie Dorais]),
		mdp: [patate],
		piscine: new_piscine(auth_partage: true, vfi: false, tete_sous_eau: true),
		auth_photo: false,
		commentaire: none,
		naissance: [2015/08/03],
		age: [9],
	),
new_enfant(
		id: "M17f5242a",
		nom: [Scott Dupont],
		prenom: [Estelle],
		cam: new_cam(nam: [SCOE16620718], exp_mois: [12], exp_year: [2024]),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Véronique Scott], tel: none, adresse: none, email: "scott.veronique\@gmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: false, ibuprofene: none, antiemetique: false, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Véronique Scott], tel: [+1 (514) 808-0797], lien: [mère]),
		contact_2: new_contact(nom: [Pascal Dupont Dorais], tel: [+1 (438) 397-2025], lien: [père]),
		quitte: ([Parent], [Autre: Isabelle Paquin, Sophie Dorais]),
		mdp: [patate],
		piscine: new_piscine(auth_partage: true, vfi: false, tete_sous_eau: true),
		auth_photo: false,
		commentaire: none,
		naissance: [2016/12/07],
		age: [8],
	),
new_enfant(
		id: "M96db7aa9",
		nom: [Tellez],
		prenom: [Alejandro],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Autre],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Carolina Tellez], tel: none, adresse: none, email: "none"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2015/01/01],
		age: [10],
	),
new_enfant(
		id: "Mc94f7715",
		nom: [Tellez],
		prenom: [Mariana],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Carolina Tellez], tel: none, adresse: none, email: "none"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2020/01/01],
		age: [5],
	),
new_enfant(
		id: "Md49e501f",
		nom: [Therrien],
		prenom: [Pierre],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [Edith Côté-Demers], tel: none, adresse: none, email: "edith.cotedemers\@hotmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2019/06/10],
		age: [5],
	),
new_enfant(
		id: "M672e5f3d",
		nom: [cote],
		prenom: [magali],
		cam: new_cam(nam: [COTM15581116], exp_mois: [08], exp_year: [2031]),
		genre: [Femme],
		allergies: ([Péniciline],),
		maladies: ([asthme seulement lors d'effort ou de rhume],),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [Julie Guilbault], tel: none, adresse: none, email: "jguilbault65\@gmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: true, ibuprofene: none, antiemetique: true, antibiotique: true, acetaminophene: true,),
		contact_1: new_contact(nom: [Dominic cote], tel: [+1 (514) 922-1622], lien: [pere]),
		contact_2: new_contact(nom: [sabrina theriault], tel: [+1 (514) 677-6474], lien: [voisine]),
		quitte: ([Parent], [Autre: jacinthe boily, grand mere]),
		mdp: [Cuistot],
		piscine: new_piscine(auth_partage: true, vfi: false, tete_sous_eau: true),
		auth_photo: true,
		commentaire: none,
		naissance: [2015/08/11],
		age: [9],
	),
new_enfant(
		id: "M9be9bcd9",
		nom: [maheu bertrand],
		prenom: [james],
		cam: new_cam(nam: none, exp_mois: none, exp_year: none),
		genre: [Homme],
		allergies: (),
		maladies: (),
		prob_comportement: none,
		compte: new_compte(mandataire: [tania morissette], tel: none, adresse: none, email: "tania_chaton2\@hotmail.com"),
		prise_med: none,
		auth_soins: none,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: none, ibuprofene: none, antiemetique: none, antibiotique: none, acetaminophene: none,),
		contact_1: none,
		contact_2: none,
		quitte: (),
		mdp: none,
		piscine: new_piscine(auth_partage: none, vfi: none, tete_sous_eau: none),
		auth_photo: none,
		commentaire: none,
		naissance: [2019/01/19],
		age: [6],
	),
new_enfant(
		id: "Me0f09851",
		nom: [mukandila-walters],
		prenom: [jasmine],
		cam: new_cam(nam: [MUKJ18542918], exp_mois: [04], exp_year: [2026]),
		genre: [Femme],
		allergies: (),
		maladies: (),
		prob_comportement: bool_just(val: false, just: none),
		compte: new_compte(mandataire: [bilonda mukandila], tel: none, adresse: none, email: "bmukandila\@hotmail.com"),
		prise_med: bool_just(val: false, just: none),
		auth_soins: true,
		medicaments: new_medicaments(anti_inflamatoire: none, sirop_toux: false, ibuprofene: none, antiemetique: false, antibiotique: false, acetaminophene: false,),
		contact_1: new_contact(nom: [Bilonda Mukandila], tel: [+1 (514) 883-8989], lien: [Mère]),
		contact_2: new_contact(nom: [Chris  Walters], tel: [+1 (514) 575-7630], lien: [Père]),
		quitte: ([Parent],),
		mdp: [3 frères],
		piscine: new_piscine(auth_partage: true, vfi: true, tete_sous_eau: false),
		auth_photo: false,
		commentaire: none,
		naissance: [2018/04/29],
		age: [7],
	),
)
#show: it => presence_sdj(
	site: site,
	saison: saison,
	semaine: semaine,
	groupes: groupes,
	participants: participants,
)